# This file was generated by the {rix} R package v0.18.1 on 2026-03-14
# with following call:
# >rix::rix(date = "2026-03-11",
#  > r_pkgs = r_pkgs,
#  > system_pkgs = c("qpdf"),
#  > git_pkgs = NULL,
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = FALSE,
#  > r_ver = "4.5.3")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-03-11.tar.gz") {};


    # engsoccerdata is marked broken in nixpkgs but goalmodel Imports it
    engsoccerdata = pkgs.rPackages.engsoccerdata.overrideAttrs (_: {
      meta = { broken = false; };
    });

    goalmodel = (pkgs.rPackages.buildRPackage {
      name = "goalmodel";
      src = pkgs.fetchgit {
        url = "https://github.com/opisthokonta/goalmodel";
        rev = "84ecd6c2bbad3ccb967abf88ef49e5bcd074e545";
        sha256 = "sha256-InAgUuPsVME4hdyGS2pQsMXFkzlPKlILNP7N6ESnjy8=";
      };
      propagatedBuildInputs = [
        engsoccerdata
      ] ++ builtins.attrValues {
        inherit (pkgs.rPackages)
          MASS
          dplyr
          Rcpp;
      };
    });

    rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages)
      arrow
      brms
      cli
      covr
      crew
      DBI
      dbplyr
      devtools
      dplyr
      DT
      duckdb
      elo
      gert
      ggplot2
      gh
      glue
      here
      httr2
      knitr
      languageserver
      lme4
      lubridate
      Matrix
      mirai
      pins
      pkgdown
      pkgload
      plotly
      probably
      quarto
      ranger
      readr
      rlang
      rmarkdown
      rsample
      scales
      scoring
      styler
      tarchetypes
      targets
      testthat
      tibble
      tidyr
      usethis
      withr
      worldfootballR;
  };

  system_packages = builtins.attrValues {
    inherit (pkgs)
      glibcLocales
      nix
      qpdf
      R
      quarto
      which
      pandoc;
  };

  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [ rpkgs goalmodel system_packages ];

    # Clear inherited R library paths from outer nix-shell.
    # Nix's R setup hook will rebuild R_LIBS_SITE from buildInputs.
    R_LIBS_SITE = "";
    R_LIBS_USER = "";

  };
in
  {
    inherit pkgs shell;
  }
