# This file was generated by the {rix} R package v0.18.1 on 2026-03-17
# with following call:
# >rix(date = "2026-03-02",
#  > r_pkgs = r_pkgs,
#  > system_pkgs = c("qpdf"),
#  > git_pkgs = NULL,
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-03-02.tar.gz") {};
 
  
    # engsoccerdata is marked broken in nixpkgs but goalmodel Imports it
    engsoccerdata = pkgs.rPackages.engsoccerdata.overrideAttrs (_: {
      meta = { broken = false; };
    });

    goalmodel = (pkgs.rPackages.buildRPackage {
      name = "goalmodel";
      src = pkgs.fetchgit {
        url = "https://github.com/opisthokonta/goalmodel";
        rev = "84ecd6c2bbad3ccb967abf88ef49e5bcd074e545";
        sha256 = "sha256-InAgUuPsVME4hdyGS2pQsMXFkzlPKlILNP7N6ESnjy8=";
      };
      propagatedBuildInputs = [
        engsoccerdata
      ] ++ builtins.attrValues {
        inherit (pkgs.rPackages)
          MASS
          dplyr
          Rcpp;
      };
    });

    rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      arrow
      bayesplot
      brms
      cli
      covr
      crew
      DBI
      dbplyr
      devtools
      dplyr
      DT
      duckdb
      elo
      gert
      ggplot2
      gh
      glue
      here
      htmltools
      httr2
      knitr
      languageserver
      lme4
      lubridate
      Matrix
      mirai
      pins
      pkgdown
      pkgload
      plotly
      probably
      purrr
      quarto
      ranger
      readr
      rlang
      rmarkdown
      rsample
      scales
      scoring
      styler
      tarchetypes
      targets
      testthat
      tibble
      tidyr
      usethis
      withr
      worldfootballR
      yaml;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      qpdf
      R
      quarto
      which
      pandoc;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs goalmodel system_packages ];

    # Prevent ABI mismatch when nix-shell is nested inside another nix-shell.
    # Inherited R_LIBS_SITE points to packages compiled against the outer R;
    # loading those .so files from the inner R causes segfaults.
    # Fix: rebuild R_LIBS_SITE from this derivation's full dependency closure.
    shellHook = ''
      R_LIBS_SITE=""
      for pkg in $buildInputs; do
        for dep in $(nix-store -qR "$pkg" 2>/dev/null); do
          if [ -d "$dep/library" ]; then
            case ":$R_LIBS_SITE:" in
              *":$dep/library:"*) ;;
              *) R_LIBS_SITE="''${R_LIBS_SITE:+$R_LIBS_SITE:}$dep/library" ;;
            esac
          fi
        done
      done
      export R_LIBS_SITE
      unset R_LIBS_USER
      unset R_LIBS
    '';
  }; 
in
  {
    inherit pkgs shell;
  }
